# Generated by Django 3.2.13 on 2022-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
